import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';
import ToastProvider from './components/Toast/ToastProvider';
import { Analytics } from "@vercel/analytics/next"

export const metadata = {
  title: 'Renvestment',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/site/favicon-32x32.png',
    apple: '/images/site/apple-touch-icon.png'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <Navbar />
          {children}
          <Analytics />
          <Footer />
        </ToastProvider>
      </body>
    </html>
  )
}
